services:
  fastapi:
    container_name: api-shavira-undiksha
    build: .
    command: uvicorn api.main:app --host=0.0.0.0 --port 3001 --workers 8 --reload
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - .:/app
